### ISSUE TITLE
Delay between rotations

### ISSUE THREAD

**Issue by tduchateau** [apax637/wordsrotator#1]
Hi,

Great plugin, thanks for your work!

I just have a tiny request: could it be possible to be able to set a delay between each rotation?

Regards,
Thibault

**Comment by apax637** [comment]
Hi, you can insert a delay between animations, using the “speed” parameter, eg.:

```
<p>An <span id="myWords"></span> a day keeps the doctor away</p>
<script type="text/javascript">
    $(function () {
        $("#myWords").wordsrotator({
            words: ['apple', 'apricot', 'avocado'],
            speed: 5000 //delay in milliseconds between two words
        });
    });
</script>
```

**Comment by tduchateau** [comment]
I expressed myself poorly. :-(
I already use the `speed` parameter for words animation. Currently, I display 3 different words.
But actually I would like to be able to set a delay between each global rotation of the 3 words.

Hope it's clearer! :-)
